FROM centos:8 as builder

WORKDIR /oslat
COPY . .

RUN dnf update -y && \
dnf install -y \
make \
gcc \
numactl-devel && \
dnf clean all

RUN make

FROM centos:8

RUN dnf update -y && \
dnf install -y numactl-libs && \
dnf clean all

# renamed to be backward compatible with the previous entry point
COPY run-oslat.sh /usr/bin/oslat
COPY --from=builder /oslat/oslat REPLACE_OSLAT_BIN

